name: Bicep to ARM

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build Bicep to ARM
      run: |
        curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        chmod +x bicep
        bicep build infra/main.bicep --outfile infra/azure-deploy.json
      shell: bash

    - name: Commit and push ARM template
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add infra
        git commit -m "Compile Bicep to ARM"
        git push -u origin HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
